version: '2'
services:
  # db:
  #   image: mysql:5.7
  #   restart: always
  #   environment:
  #     MYSQL_ROOT_PASSWORD: password
  #     MYSQL_DATABASE: hackerhero
  #     MYSQL_USER: appuser
  #     MYSQL_PASSWORD: password
  #   ports:
  #     - "3307:3306"

  app:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ".:/hackerhero"
    ports:
      - "3001:3000"
    # depends_on:
    #   - db
    # links:
    #   - db
    # environment:
    #    DB_USER: remote_user
    #	DB_NAME: hackerheroinstance
    #	DB_PASSWORD: village88
    #	DB_HOST: hackerheroinstance.c1zhyimslpmo.us-west-1.rds.amazonaws.com
